name: Release

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: ğŸ›ï¸ Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # All history for branches and tags

      - name: ğŸ“¦ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: ğŸ› ï¸ Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: pnpm

      - name: ğŸ“‚ Install Dependencies
        run: pnpm i

      - name: ğŸ§ Check Code Quality
        run: pnpm lint

      # - name: ğŸ­ Install Playwright
      #   run: pnpm i playwright http-server wait-on; npx playwright install --with-deps

      # - name: ğŸ“” Build Storybook
      #   run: pnpm build-storybook --quiet

      # - name: ğŸ§ª Serve Storybook and run tests
      #   run: |
      #     pnpx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
      #       "pnpm exec http-server storybook-static --port 6006 --silent" \
      #       "pnpm exec wait-on tcp:6006 && pnpm test-storybook"

      # - name: ğŸ”¬ Run Unit Tests
      #   run: pnpm jest ...

      # - name: ğŸ” Run Integration Tests
      #   run: pnpm jest ...

      # - name: âŒš ğŸ’€ Run E2E Tests
      #   run: pnpx playwright test

      # - name: ğŸ‘€ Run Visual Tests
      #   env:
      #     CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #   run: pnpm run chromatic

      - name: ğŸ—ï¸ Build Project
        # env:
        #   SANITY_API_READ_TOKEN: ${{ secrets.SANITY_API_READ_TOKEN }}
        run: pnpm build

      - name: ğŸ¤– Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm exec semantic-release

      - name: ğŸ’° Profit
        run: echo ğŸ
